name: CI

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '8' ]
        os: [ 'ubuntu-latest', 'macOS-latest' ]

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JVM
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Run install
        # Skip tests because we require the install before the publish
        # we'll then test right after
        run: ./mvnw clean install -DskipTests

      - name: Run tests
        run: ./mvnw test
