name: release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Apache Maven Central
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
        server-id: maven # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.PGP_SECRET }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_PGP_PASSPHRASE # env variable for GPG private key passphrase

    - name: Publish to Apache Maven Central
      run: ./mvnw deploy
      env:
        MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
