name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Apache Maven Central
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
        server-id: central # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
        gpg-private-key: ${{ secrets.PGP_SECRET }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

    # Even using -DskipTests cause tests to run in the release it seems
    - name: Install so tests can pass in the release 
      run: mvn install -DskipTests

    - name: Setup git profile
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "123456+github-actions[bot]@users.noreply.github.com"

    - name: Publish to Apache Maven Central
      run: mvn release:prepare release:perform -DskipTests -DreleaseVersion=${{github.event.inputs.version}} -Prelease
      env:
        MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
